version: '3'


services:      
  recvfile:
    image: udt/recv:latest
    env_file: .env
    build:
      dockerfile: ./Dockerfile-UDT recv
      context: .
    networks:
      ns3_ext:
        ipv4_address: 10.1.1.101
      ns3_client:
        ipv4_address: 192.168.42.101
    cap_add:
      - NET_ADMIN
    depends_on:
      - ns3-box
      - sendfile
    volumes:
      - ./out_files:/result
      
  sendfile:
    image: udt/send:latest
    build:
      dockerfile: ./Dockerfile-UDT send
      context: .
    networks:
      ns3_ext:
        ipv4_address: 10.1.1.103
      ns3_server:
        ipv4_address: 192.168.44.101
    expose:
      - "6121/udp"
    ports:
      - "6121:6121/udp"
    cap_add:
      - NET_ADMIN
    depends_on:
      - ns3-box
      
  ns3-box:
    image: ns3-box:latest
    env_file: .env
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./out_dumps:/ns3/dumps
    networks:
      ns3_ext:
        ipv4_address: 10.1.1.104
      ns3_client:
      ns3_server:
      
#
# Если сети уже созданы
#      
#networks:
#  ns3_ext:
#    external: true    
#  ns3_client:
#    external: true    
#  ns3_server:
#    external: true 
    
networks:
  ext:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
    enable_ipv6: false
  client:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.42.0/24
    enable_ipv6: false
  server:
    ipam:
      driver: default
      config:
        - subnet: 192.168.44.0/24
    enable_ipv6: false   